export default  [
    "Blonde Escorts",
    "BDSM/Fetish Providers",
    "Disability Friendly Escorts",
    "Doubles Escorts",
    "Enhanced Breasts Escorts",
    "Erotic Massage",
    "Fitness Escorts",
    "GFE Escorts",
    "Fly Me To You Escorts",
    "Mature Escorts",
    "Slim Escorts",
    "Brunette Escorts",
    "Milf Escorts",
    "Natural Breasts Escorts",
    "No tattoo Escorts",
    "Pierced Escorts",
    "Red Hair Escorts",
    "Pregnant Escorts",
    "Tantra Escorts",
    "Busty Escorts",
    "PSE Escorts",
    "Submissive Escorts",
    "Tall Escorts",
    "Tattooed Escorts",
    "Young Escorts",
    "Touring Escorts",
  ];