export default [
    "Anal",
    "AB/DL",
    "Adult Babies",
    "Affectionate Cuddling",
    "Affectionate Kissing",
    "Anal Play",
    "Anal Play - On Me",
    "Anal Play - On You",
    "ATM - Ass To Mouth",
    "B + D - Bondage + Discipline",
    "Ball Busting",
    "BBBJ - Bare Back Blow Job",
    "BBW - Big Beautiful Woman",
    "BDSM",
    "Begging",
    "Beginners",
    "BFE - Boyfriend Experience",
    "Bi Twin (double)",
    "Biting",
    "BJ - Blow Job",
    "BLS - Balls Licking & Sucking",
    "Body Worship",
    "Bondage",
    "Brats",
    "Brazilian",
    "Breastfeeding",
    "Brown Showers",
    "BS - Body Slide",
    "Caning",
    "CBJ - Covered Blow Job",
    "CBT - Cock & Ball Torture",
    "CBT - Cock & Ball Torture",
    "CD - Cross Dressing",
    "Chastity",
    "CIM - Cum In Mouth",
    "CIMWS - Mum In Mouth With Swallow",
    "COB - Cum On Body",
    "Cock Worship",
    "COF - Cum On Face",
    "Collars",
    "Corporal Punishment",
    "Costumes",
    "Costumes & Role Play",
    "Cougar",
    "Couples",
    "Cross Dressing",
    "Cuckolding",
    "DATY - Oral On Me",
    "D/S",
    "Daddy Dom / lg",
    "DDP - Double Digit Penetration",
    "DFK - Deep French Kissing",
    "Dinner Companion",
    "Dirty Talk",
    "Disabled Clients",
    "Discipline",
    "Doggy Style",
    "Domestic Service",
    "Double Domme",
    "Dominant",
    "DP - Double Penetration",
    "DT - Deep Throat",
    "Edging",
    "Electro Play",
    "Enema Play",
    "Erotic Domination",
    "Erotic Sensual Massage",
    "Face Sitting",
    "Face Slapping",
    "Facial - Cum On Face",
    "FE - Female Ejaculation (squirting)",
    "femdom",
    "Fetish",
    "Filming",
    "Financial Domination",
    "Fire & Ice - Hot & Cold BJ",
    "Fisting",
    "Fisting Anal",
    "Fisting Vaginal",
    "FK - French Kissing",
    "Flogging",
    "Fly Me To You",
    "Foot Fetish",
    "Forced Feeding",
    "FS - Full Service",
    "Full Oil Massage",
    "Gagging",
    "GFE - Girlfriend Experience",
    "Greek - Anal Sex",
    "GS - Golden Showers",
    "GS - Golden Shower - On me",
    "GS - golden shower - On you",
    "Hair Pulling",
    "Happy Ending",
    "HJ - Hand Job",
    "Human Furnture",
    "Humiliation",
    "Impact Play",
    "Italian",
    "kinky GFE",
    "Kissing",
    "Lactating (before/after pregnancy)",
    "Latex",
    "Leather",
    "Lesbian / Bisexual (Female To Female)",
    "Light Bondage",
    "Light Spanking",
    "Lingerie",
    "LK - Light Kissing",
    "Maid",
    "Massage",
    "Master/Slave",
    "Masturbation",
    "Medical Play",
    "MFF - Male Female Female",
    "MILF - Mother I’d Like To Fuck",
    "Mind Fucking",
    "Mistress Slave",
    "MMF - Male Male Female",
    "MSOG - Multiple Shots On Goal",
    "Multiple Positions",
    "Mummification",
    "Muscle Worship",
    "Mutual French (oral)",
    "Mutual Masturbation",
    "Mutual Natural Oral",
    "Natural Bush (pubic hair)",
    "Natural Oral",
    "Needle Play",
    "Nipple Play",
    "Nipple Torture",
    "Nurse",
    "Nuru",
    "Objectification",
    "Orgasm Control",
    "Orgasm Denial",
    "Overnight Stays",
    "Pain",
    "Panties",
    "Passionate Kissing",
    "Pearl Necklace",
    "Pet Play",
    "Photography",
    "Police Woman",
    "Power Dynamics",
    "Pregnant",
    "Pro-Submissive",
    "Prostate Massage",
    "Prostate Milking",
    "Prostate Play",
    "PSE - Porn Star Experience",
    "PSE - Porn Star Experience - With Filming",
    "Pussy Pump",
    "Rimming",
    "Rimming - On Me",
    "Rimming - On You",
    "Role Play",
    "Roman Showers",
    "Roman Showers (vomit fetish)",
    "Ruby Showers",
    "Ruined Orgasm",
    "Sadistic",
    "School Girl",
    "Scratching",
    "Secretary",
    "Seduction",
    "Sensory Deprivation",
    "Sensory Stimulation",
    "Sensual Domination",
    "Service Training",
    "Sex Toys",
    "Sexy Lingerie",
    "Sexy Shower For 2",
    "Shaving",
    "Shibari",
    "Shoe Worship",
    "Sissification",
    "Slave Training",
    "Smoking Fetish",
    "Smothering",
    "Snowballing",
    "Social Escort",
    "Social Outings",
    "Sounding",
    "Spanish",
    "Spanking - On Me",
    "Spanking - On You",
    "Spitting",
    "Squirting",
    "Strap On",
    "Strap On - On Me",
    "Strap On - On You",
    "Strip Tease",
    "Strong Women",
    "Tantra",
    "Tea Bagging",
    "Tease & Denial",
    "Throat Holding",
    "Tickling",
    "Tie & Tease",
    "Toilet Training",
    "Trampling",
    "Travel Companion",
    "Tromboning",
    "Wet & Messy",
    "Whipping",
    "Women",
    "Wrestling",
    "Wax Play",
    "Watersports",
    "Verbal Humiliation",
  ];